apiVersion: apps/v1
kind: Deployment
metadata:
  name: studybuddy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: studybuddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: studybuddy
    spec:
      containers:
        - name: eureka-pod
          image: docker.io/brc/eureka
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
        - name: gateway-pod
          image: docker.io/brc/gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
        - name: auth-pod
          image: docker.io/brc/auth
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
        - name: users-pod
          image: docker.io/brc/users
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
        - name: groups-pod
          image: docker.io/brc/groups
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
        - name: meetings-pod
          image: docker.io/brc/meetings
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: studybuddy
spec:
  ports:
    - name: eureka
      port: 8761
      protocol: TCP
      targetPort: 8761
    - name: gateway
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: studybuddy
  type: ClusterIP
