apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eureka-web
    spec:
      containers:
        - name: eureka-pod
          image: docker.io/brc/eureka
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-web
  labels:
    app.kubernetes.io/name: eureka-web
spec:
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app.kubernetes.io/name: eureka-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-web
    spec:
      containers:
        - name: gateway-pod
          image: docker.io/brc/gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"instance": {"preferIpAddress": true, "hostname": "gateway-web"}, "client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-web
  labels:
    app.kubernetes.io/name: gateway-web
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: gateway-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-web
    spec:
      containers:
        - name: auth-pod
          image: docker.io/brc/auth
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"instance": {"preferIpAddress": true, "hostname": "auth-web"}, "client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-web
  labels:
    app.kubernetes.io/name: auth-web
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: auth-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: users-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-web
    spec:
      containers:
        - name: users-pod
          image: docker.io/brc/users
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"instance": {"preferIpAddress": true, "hostname": "users-web"}, "client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: users-web
  labels:
    app.kubernetes.io/name: users-web
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app.kubernetes.io/name: users-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: groups-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: groups-web
    spec:
      containers:
        - name: groups-pod
          image: docker.io/brc/groups
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"instance": {"preferIpAddress": true, "hostname": "groups-web"}, "client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: groups-web
  labels:
    app.kubernetes.io/name: groups-web
spec:
  ports:
  - name: 8083-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app.kubernetes.io/name: groups-web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meetings-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meetings-web
    spec:
      containers:
        - name: meetings-pod
          image: docker.io/brc/meetings
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"instance": {"preferIpAddress": true, "hostname": "meetings-web"}, "client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: meetings-web
  labels:
    app.kubernetes.io/name: meetings-web
spec:
  ports:
  - name: 8084-8084
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app.kubernetes.io/name: meetings-web
  type: ClusterIP
