#
# Eureka Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-web
  creationTimestamp: null
  labels:
    app: eureka-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka-web
    spec:
      containers:
        - name: eureka-pod
          image: docker.io/brc/eureka
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-web
  labels:
    project: brc
spec:
  ports:
    - name: 8761-8761
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: eureka-web
  type: ClusterIP
---
#
# Gateway Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-web
  creationTimestamp: null
  labels:
    app: gateway-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway-web
    spec:
      containers:
        - name: gateway-pod
          image: docker.io/brc/gateway
          imagePullPolicy: Never
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-web
  labels:
    project: brc
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway-web
  type: ClusterIP
---
#
# Auth Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
  creationTimestamp: null
  labels:
    app: auth-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-web
    spec:
      containers:
        - name: auth-pod
          image: docker.io/brc/auth
          imagePullPolicy: Never
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-web
  labels:
    project: brc
spec:
  ports:
    - name: 8081-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: auth-web
  type: ClusterIP
---
#
# Users Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-web
  creationTimestamp: null
  labels:
    app: users-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: users-web
    spec:
      containers:
        - name: users-pod
          image: docker.io/brc/users
          imagePullPolicy: Never
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: users-web
  labels:
    project: brc
spec:
  ports:
    - name: 8082-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: users-web
  type: ClusterIP
---
#
# Groups Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-web
  creationTimestamp: null
  labels:
    app: groups-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groups-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: groups-web
    spec:
      containers:
        - name: groups-pod
          image: docker.io/brc/groups
          imagePullPolicy: Never
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: groups-web
  labels:
    project: brc
spec:
  ports:
    - name: 8083-8083
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: groups-web
  type: ClusterIP
---
#
# Meetings Microservice
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetings-web
  creationTimestamp: null
  labels:
    app: meetings-web
    project: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetings-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meetings-web
    spec:
      containers:
        - name: meetings-pod
          image: docker.io/brc/meetings
          imagePullPolicy: Never
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka": {"client": {"service-url": {"defaultZone": "http://eureka-web:8761/eureka"}}}, "spring": {"config": {"import": "optional:configserver:http://eureka-web:8761"}}}'
---
apiVersion: v1
kind: Service
metadata:
  name: meetings-web
  labels:
    project: brc
spec:
  ports:
    - name: 8084-8084
      port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: meetings-web
  type: ClusterIP
