# See any common application properties in
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# ----------------------------------------------------------------------------------------------
#                                       Server Configurations
# ----------------------------------------------------------------------------------------------
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# ----------------------------------------------------------------------------------------------
#                                       Spring Configurations
# ----------------------------------------------------------------------------------------------
spring:
  application:
    name: "gateway"
  # Gateway configurations
  cloud:
    gateway:
      enabled: true
      routes:
        - id: "auth"
          uri: "lb://auth"
          predicates:
            - "Path=/auth/**"
        - id: "users"
          uri: "lb://users"
          predicates:
            - "Path=/users/**"
        - id: "groups"
          uri: "lb://groups"
          predicates:
            - "Path=/groups/**"
        - id: "template"
          uri: "lb://template"
          predicates:
            - "Path=/template/**"

# ----------------------------------------------------------------------------------------------
#                                       Eureka Configurations
# ----------------------------------------------------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
