# See any common application properties in
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# server.error.whitelabel.enabled=false

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080/auth # TODO: Change Obviously
          predicates:
            - Path=/auth/**
      enabled: true