# See any common application properties in
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# ----------------------------------------------------------------------------------------------
#                                       Server Configurations
# ----------------------------------------------------------------------------------------------
server:
  port: 8081
  error:
    whitelabel:
      enabled: false

# ----------------------------------------------------------------------------------------------
#                                       Spring Configurations
# ----------------------------------------------------------------------------------------------
spring:
  application:
    name: "auth"

# ----------------------------------------------------------------------------------------------
#                                       Custom Configurations
# ----------------------------------------------------------------------------------------------
secrets:
  key: "asdkfja82345n23489fdshnf894nfjanf094u3n34f9fnjanf09u43nf43jknf0a97sdhfshdflakjsdhf"
  ttl: 300000 # time to live in milliseconds for each token
  facebook:
    apptoken: "475499464360666|9f81835d84d715b51845635fd481ff25"
# ----------------------------------------------------------------------------------------------
#                                       Eureka Configurations
# ----------------------------------------------------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
