# See any common application properties in
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# ----------------------------------------------------------------------------------------------
#                                       Server Configurations
# ----------------------------------------------------------------------------------------------
server:
  port: 8081
  error:
    whitelabel:
      enabled: false

# ----------------------------------------------------------------------------------------------
#                                       Spring Configurations
# ----------------------------------------------------------------------------------------------
spring:
  application:
    name: "auth"
  # Config-Server configurations
  config:
    import: "optional:configserver:http://localhost:8761" # Same as "eureka.client.service-url.defaultZone"

# ----------------------------------------------------------------------------------------------
#                                       Custom Configurations
# ----------------------------------------------------------------------------------------------
auth:
  refresh:
    # Time to live for the fresh token. It is added to the authentication token's ttl
    # In other words: ttl = authentication.ttl + refresh.ttl
    ttl: 120
  facebook:
    apptoken: "475499464360666|9f81835d84d715b51845635fd481ff25"

# ----------------------------------------------------------------------------------------------
#                                       Eureka Configurations
# ----------------------------------------------------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
